### ISSUE TITLE
scrollTop Decode int or float?

### ISSUE THREAD

**Issue by pablohirafuji** [FabienHenon/elm-infinite-scroll#12]
Hey, nice package, thanks for publishing it!

Looking at the source, I saw that you used `Json.Decode.int` to decode the `scrollTop` value from javascript, but looking at the [specs](https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface), it can return a float and there is a warning on the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) page about it also. If this happen, it will fail silently.

I'm not having issues with this currently (Chrome 69), but is something to keep an eye on in case some browser change the behavior to follow the spec.

**Comment by FabienHenon** [comment]
Hi, thank you!

If I remember correctly I looked at another package's source code to find out how to retrieve the `scrollTop` value.
I guess decoding as a float can't do anything wrong. 
Would you mind submitting a PR?
