### ISSUE TITLE
Pagination example

### ISSUE THREAD

**Issue by simonmclean** [FabienHenon/elm-infinite-scroll#14]
I'm struggling to figure out how to handle pagination with this package.

It seems like `loadMoreCmd` is the solution, but none of the examples in the repo use it.

There's this snippet in the documentation:

```
newRequest page =
    Task.perform OnLoadMore <| Task.succeed page

{ model | infiniteScroll =
    model.infiniteScroll
        |> loadMoreCmd (newRequest model.page)
}
```

But between the use of `Task`, and the reference to an unspecified `loadMoreCmd`, I'm unclear how this would fit with the tutorial and examples in the readme. 

Would it possible to get a basic but complete example of its usage within an application?

**Comment by FabienHenon** [comment]
Hi,

The examples show a working infinite scroll with queries to a HTTP server (like this one https://github.com/FabienHenon/elm-infinite-scroll/blob/master/examples/TopScroll.elm)

If you need to keep a variable with the current page, all you need is to call the function [`loadMoreCmd`](https://package.elm-lang.org/packages/FabienHenon/elm-infinite-scroll/latest/InfiniteScroll#loadMoreCmd) as soon as you change your current page to update the loadMore function (which is called automatically when the scroll bar hits the threshold)

For instance, assuming you have a `Msg` `OnDataReceived` that handles the new data you receive from your API. In your update function you could do something like this:

```
update msg model =
    case msg of
        OnDataReceived (Ok data) ->
            ( { model | data = model.data ++ data, currPage = model.currPage + 1, infiniteScroll = model.infiniteScroll |> InfiniteScroll.loadMoreFunc (loadMore (model.currPage + 1)) }, Cmd.none )

loadMore : Int -> InfiniteScroll.Direction -> Cmd Msg
loadMore currPage direction =
    -- Your request to retrieve your data goes here
    Http.get ("url/" ++ (String.fromInt currPage))
```

The `loadMore` function will be called automatically when the `InfiniteScroll` package thinks more data should be retrieved. Then that's up to you to update your `loadMore` function with some contextual parameters like the current page.

**Comment by simonmclean** [comment]
Thanks @FabienHenon . `infiniteScroll = model.infiniteScroll |> InfiniteScroll.loadMoreFunc (loadMore (model.currPage + 1))` is what I was looking for
