### ISSUE TITLE
Multiple infinite scroll on a page possible?

### ISSUE THREAD

**Issue by girishso** [FabienHenon/elm-infinite-scroll#9]
Is it possible to have two infinite scrolling elements on the same page?

**Comment by girishso** [comment]
Tried modifying an example with two scrollers. Strangely second scroll fires Msg for first scroller, can't figure out why.

https://gist.github.com/girishso/4402d31347cb5ce3581be18249ed985b

**Comment by FabienHenon** [comment]
There should be nothing preventing `InfiniteScroll` to be used multiple times in the same page.

In your gist you have a typo on line 71, you used the msg `InfiniteScrollMsg` instead of `InfiniteScrollMsg2`
Maybe this should fix your issue

**Comment by girishso** [comment]
@FabienHenon it fixed it. Awesome! Thank you!
